wget https://drive.google.com/uc?export=download&confirm=g7y0&id=1nlDdKajIjFLqHlMe3_OMrlgUxPT7BFpz
unzip shapenetcore_partanno_segmentation_benchmark_v0.zip
rm shapenetcore_partanno_segmentation_benchmark_v0.zip
